name: Bug Report
description: Report a bug that needs to be fixed
title: "[BUG]: "
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide all the required information to help us understand and process your issue efficiently.

  - type: dropdown
    id: master_component
    attributes:
      label: Master Component
      description: Select the project component this issue should be assigned to
      options:
        - ACCESSCONTROL
        - ANSIBLE
        - CCE
    validations:
      required: true

  - type: textarea
    id: users_impact
    attributes:
      label: User's Impact
      description: Describe how this issue impacts users
      placeholder: "Example: Users cannot access their data when..."
    validations:
      required: true

  - type: checkboxes
    id: affected_locations
    attributes:
      label: Affected Location(s) ⭐ REQUIRED
      description: Select the affected locations (at least one must be selected)
      options:
        - label: "EU-DE-01 AZ1 (Germany/Biere)"
        - label: "EU-DE-02 AZ2 (Germany/Magdeburg)"
        - label: "EU-DE-03 AZ3 (Germany/Biere)"
        - label: "EU-NL-01 Amsterdam AZ1 (Netherlands/Amsterdam AMS2)"
        - label: "EU-NL-02 Amsterdam AZ2 (Netherlands/Amsterdam AMS3)"
        - label: "EU-NL-03 Amsterdam AZ3 (Netherlands/Amsterdam AMS2)"
        - label: "EU-CH2-01 SwissCloud AZ1 (Switzerland/Zollikofen)"
        - label: "EU-CH2-02 SwissCloud AZ2 (Switzerland/Bern)"
        - label: "EU-CH2-03 SwissCloud AZ3 (Switzerland/Zollikofen)"
    validations:
      required: true

  - type: dropdown
    id: test_category
    attributes:
      label: Test Category
      description: Select the testing category that applies to this issue
      options:
        - QA
        - UAT
        - Security
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: Select the priority level of this issue
      options:
        - Blocker
        - Low
        - Medium
        - High
    validations:
      required: true

  - type: checkboxes
    id: bug_type
    attributes:
      label: Bug Type ⭐ REQUIRED
      description: Select the type of bug (at least one must be selected)
      options:
        - label: Documentation
        - label: API
        - label: UI
        - label: Billing
        - label: Platform
        - label: Security
        - label: "Price Calculator"
        - label: "External TSI"
        - label: "API Standardization"
    validations:
      required: true

  - type: checkboxes
    id: affected_areas
    attributes:
      label: Affected Area(s) ⭐ REQUIRED
      description: Select areas affected by this issue (at least one must be selected)
      options:
        - label: Production
        - label: PreProd
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide detailed information about the bug
      value: test
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (logs, screenshots, etc.)
      placeholder: "Logs, error messages, screenshots, environment details..."
    validations:
      required: false