name: Feature Change
description: Request change for a feature
title: "[CHANGE]: "
labels: ["change"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature demand! Please provide all the required information to help us understand and process your request efficiently.

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Please provide a short summary to your request
      placeholder: "Please..."
    validations:
      required: true

  - type: dropdown
    id: master_component
    attributes:
      label: Master Component
      description: Select the project component this issue should be assigned to
      options:
        - ACCESSCONTROL
        - ANSIBLE
        - APIGW
        - CCE
        - ECS
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: Please provide a clear and detailed description of the feature you're requesting
      placeholder: "Describe the feature you'd like to see implemented..."
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: Select the priority level of this demand
      options:
        - Blocker
        - Minor
        - Lowest
        - Low
        - Medium
        - High
        - Highest
    validations:
      required: true

  - type: dropdown
    id: capacity_expansion
    attributes:
      label: Capacity Expansion
      description: Please set the capacity expansion
      options:
        - No
        - Yes - Existing Flavor
        - Yes - New Flavor
    validations:
      required: true

  - type: dropdown
    id: night_time_change
    attributes:
      label: Night Time Change
      description: If this change must be scheduled and executed during non-business hours
      options:
        - No
        - Yes
    validations:
      required: true

  - type: dropdown
    id: customer_impact
    attributes:
      label: Customer Impact
      description: Change classification
      options:
        - No
        - Yes
    validations:
      required: true

  - type: textarea
    id: change_duration
    attributes:
      label: Change Duration
      description: The estimated time the change will be implemented in hours
      placeholder: "... hours"
    validations:
      required: true

  - type: textarea
    id: risk_of_omission
    attributes:
      label: Risk of Omission
      description: Risk to NOT install the change
    validations:
      required: true

  - type: textarea
    id: risk_of_implementation
    attributes:
      label: Risk of Implementation
      description: Risk of implementing the change
    validations:
      required: true

  - type: textarea
    id: change_scope
    attributes:
      label: Change Scope
      description: Change Scope
    validations:
      required: true
