name: Feature Release
description: Request release of a new feature
title: "[RELEASE]: "
labels: ["release"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature demand! Please provide all the required information to help us understand and process your request efficiently.

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Please provide a short summary to your request
      placeholder: "Please..."
    validations:
      required: true

  - type: dropdown
    id: master_component
    attributes:
      label: Master Component
      description: Select the project component this issue should be assigned to
      options:
        - ACCESSCONTROL
        - ANSIBLE
        - APIGW
        - CCE
        - ECS
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: Please provide a clear and detailed description of the feature you're requesting
      placeholder: "Describe the feature you'd like to see implemented..."
    validations:
      required: true

  - type: dropdown
    id: fix_versions
    attributes:
      label: Fix Version(s)
      description: Start typing to get a list of possible matches or press down to select.
      options:
        - December 2024
        - January 2025
        - February 2025
        - March 2025
        - April 2025
        - May 2025
        - June 2025
        - July 2025
        - August 2025
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: Select the priority level of this demand
      options:
        - Blocker
        - Minor
        - Lowest
        - Low
        - Medium
        - High
        - Highest
    validations:
      required: true
