name: Helm Chart Dependencies Check

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'kubernetes/argocd-apps/system/**/Chart.yaml'

jobs:
  check-and-create-prs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml requests gitpython packaging

      - name: Run Helm dependency update check
        id: dependency-check
        run: python .github/scripts/check_helm_dependencies.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CHART_PATH: "kubernetes/argocd-apps/system"

      - name: Check for changes and create PRs
        if: ${{ fromJSON(steps.dependency-check.outputs.has_updates) }}
        run: |
          # Get info from matrix
          MATRIX='${{ steps.dependency-check.outputs.matrix }}'
          
          # Install Github cli
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh
          
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
          
          # Use vars for further tasks
          APP_NAMES=($(echo $MATRIX | jq -r '.include[].app_name'))
          BRANCH_NAMES=($(echo $MATRIX | jq -r '.include[].branch_name'))
          PR_TITLES=($(echo $MATRIX | jq -r '.include[].pr_title'))
          UPDATE_DETAILS=($(echo $MATRIX | jq -r '.include[].update_details'))
          
          # Use vars for each app!
          for i in "${!APP_NAMES[@]}"; do
            APP=${APP_NAMES[$i]}
            BRANCH=${BRANCH_NAMES[$i]}
            TITLE=${PR_TITLES[$i]}
            DETAILS=${UPDATE_DETAILS[$i]}
            
            echo "Processing $APP..."
          
            git checkout -b $BRANCH
            git add kubernetes/argocd-apps/system/$APP/Chart.yaml
            if [[ $(git diff --cached --name-only | wc -l) -gt 0 ]]; then
              git commit -m "Update Helm chart dependencies for $APP"
              git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git $BRANCH
              gh pr create --base main --head $BRANCH --title "$TITLE" --body "$DETAILS" --label "dependencies,helm-charts,$APP"
            else
              echo "No changes for $APP, skipping PR creation"
            fi
            
            git checkout main
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}