name: Helm Chart Dependencies Check

on:
#  schedule:
#    - cron: '0 9 * * 1'
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'kubernetes/argocd-apps/system/**/Chart.yaml'

jobs:
  check-helm-dependencies:
    runs-on: ubuntu-latest
    outputs:
      has_updates: ${{ steps.dependency-check.outputs.has_updates }}
      matrix: ${{ steps.dependency-check.outputs.matrix }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml requests gitpython packaging

      - name: Run Helm dependency update check
        id: dependency-check
        run: python .github/scripts/check_helm_dependencies.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CHART_PATH: "kubernetes/argocd-apps/system"

  # Job for dedicated PR create for each app
  create-prs:
    needs: check-helm-dependencies
    if: ${{ fromJSON(needs.check-helm-dependencies.outputs.has_updates) }}
    runs-on: ubuntu-latest

    strategy:
      matrix: ${{ fromJSON(needs.check-helm-dependencies.outputs.matrix) }}
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check for changes
        id: git-check
        run: |
          git status
          git diff
          CHANGES=$(git status --porcelain | wc -l)
          echo "has_changes=$CHANGES" >> $GITHUB_OUTPUT

      - name: Commit changes if any
        if: steps.git-check.outputs.has_changes != '0'
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add .
          git commit -m "Update helm chart dependencies for ${{ matrix.app_name }}"

      - name: Create Pull Request
        if: steps.git-check.outputs.has_changes != '0'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update ${{ matrix.app_name }} helm chart dependencies"
          title: ${{ matrix.pr_title }}
          body: ${{ matrix.update_details }}
          branch: ${{ matrix.branch_name }}
          delete-branch: true
          labels: dependencies, helm-charts, ${{ matrix.app_name }}
